// import React from 'react';
// import Head from 'next/head'
// import Image from 'next/image'
// import Layout from '../components/Layout';
// import { Box, Button, Avatar, Divider, Flex } from "@chakra-ui/react"

// const Dashboard = () => {
//     return (
//     	<Box>
//     	<Head>
// 	        <title>Create Next App</title>
// 	        <meta name="description" content="Generated by create next app" />
// 	        <link rel="icon" href="/favicon.ico" />
// 	      </Head>
//         <Layout>
//         <div>	ABOuT THIS BOOK</div>
//           {/*<Flex>
//         	<Box w="30%" bg="white" h="500px" position="relative">
//         		<Avatar name="Anonymous" src="dp.png" size="lg"/> 
//         		<Divider/>
//         		<Box>Overview</Box>
//         		<Box>My Uploaded Books</Box>
//         		<Box>My Purchased Books</Box>
//         		<Button 
//         			variant="outline" 
//         			position="absolute" 
//         			colorScheme="linear-gradient(225deg, #192038 0%, #2E3A59 100%)"
//         			bottom="20px"
//         		>Upload</Button>

//         	</Box>
//         	<Box w="60%">
        		
//         	</Box>
//           </Flex>*/}
//         </Layout>
//         </Box>
//     );
// };

// export default Dashboard;
