import Head from 'next/head'
import Preloader from '../components/Preloader/preloader'
import Timer from '../components/Countdown/Timer'
import { Box, Flex } from '@chakra-ui/react'
import { Heading, Text } from '@chakra-ui/react'
import ConnectButton from '../components/ConnectButton'
import FeatureCard from '../components/Home/FeatureCard'
import { MdOutlineEnhancedEncryption } from "react-icons/md"
import { GiReceiveMoney } from "react-icons/gi"
import { BiPurchaseTag } from "react-icons/bi"
import { SiSimpleanalytics } from "react-icons/si"

export default function Home() {
  return (
    <>
      <Head>
        <title> Delibra </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        {/* Hero section */}
        <Box
          bg="linear-gradient(98.41deg, #02081F 0%, #1A0830 96.87%)"
          width="100vw"
          height="100vh"
        >
          <ConnectButton/>
        </Box>

        {/* Our features section */}
        
        <Box
          bg="#ffffff"
          width="100vw"
          minH="50vh"
          px="100px"
          py={10}
        >
            <Text
              bgGradient="linear-gradient(115.03deg, #FFB0BD 6.95%, #FFC2A1 89.09%)"
              bgClip='text'
              fontSize="20px"
              fontweight="500"
              mb={5}
            >Our Features</Text>
            <Heading
              fontFamily="'Clash Grotesk', sans-serif"
              fontSize="56px"
              fontweight="700"
              mb={5}
            >Lorem ipsum dolor sit amet</Heading>
            <Text
              fontFamily="'Inter', sans-serif"
              fontSize="20px"
              fontweight="400"
              mb={5}
            >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id dictum augue mi vestibulum tempor. </Text>

            <Flex justify="space-between" my={10}>
                <FeatureCard
                  icon={<MdOutlineEnhancedEncryption/>}
                  title="Book encryption"
                  cont="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id dictum augue mi vestibulum tempor. "
                />

                <FeatureCard
                  icon={<GiReceiveMoney/>}
                  title="Read to earn"
                  cont="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id dictum augue mi vestibulum tempor. "
                />

                <FeatureCard
                  icon={<BiPurchaseTag/>}
                  title="Ease of purchase"
                  cont="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id dictum augue mi vestibulum tempor. "
                />

                <FeatureCard
                  icon={<SiSimpleanalytics/>}
                  title="Book Analytics"
                  cont="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id dictum augue mi vestibulum tempor. "
                />
            </Flex>
        </Box>
        <Preloader />
      </Box>
    </>
  )
}
